name: Build docker image

on:
  release:
    types: [published]
  push:
    branches:
      - docker

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/xray-core
          flavor: latest=auto
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Docker metadata Loyalsoldier flavor
        id: loyalsoldier
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/xray-core
          flavor: |
            latest=auto
            suffix=-loyalsoldier,onlatest=true
            suffix=-l,onlatest=true
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm
            linux/arm64
            linux/loong64
            linux/mips
            linux/mips64
            linux/mips64le
            linux/mipsle
            linux/ppc64
            linux/ppc64le
            linux/riscv64
            linux/s390x
          provenance: false
          file: .github/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Build and push Loyalsoldier flavor
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm
            linux/arm64
            linux/loong64
            linux/mips
            linux/mips64
            linux/mips64le
            linux/mipsle
            linux/ppc64
            linux/ppc64le
            linux/riscv64
            linux/s390x
          provenance: false
          file: .github/docker/Dockerfile
          build-args: flavor=loyalsoldier
          push: true
          tags: |
            ${{ steps.loyalsoldier.outputs.tags }}
